### ISSUE TITLE
Associated Paper

### ISSUE THREAD

**Issue by finnSartoris** [donghwijung/LoRCoN-LO#1]
Thanks for publishing your code. Can you also publish your submitted paper on arXiv or something? I am very interested in your work and would like to read more about it. Thanks a lot!

**Comment by donghwijung** [comment]
Thank you for your interest in my paper.
The paper has been submitted for review at IROS 2022. Therefore, we will consider whether to publish the paper after the review results are announced.
Thanks for the nice suggestion :)
